### ISSUE TITLE
vis_heuristics_net bgcolor does not overwrite default

### ISSUE THREAD

**Issue by AntonyRLee** [process-intelligence-solutions/pm4py#420] opened 2023-06-29 18:03 UTC
I cannot get the background of the heuristic net to change from white (default). Does not work for saving net either. 

Example:
import pm4py
log = pm4py.read_xes("running-example.xes")
hn = pm4py.discover_heuristics_net(log)
pm4py.view_heuristics_net(hn, bgcolor='red') # background unchanged

**Comment by fit-alessandro-berti** [comment] 2023-06-30 05:45
Dear @AntonyRLee 

Thanks for signaling. We'll release a fix in the upcoming release.

Cheers

**Comment by fit-alessandro-berti** [comment] 2023-06-30 14:44
The issue is resolved in pm4py 2.7.5

**Closed as completed by fit-alessandro-berti** 2023-06-30 14:44 UTC
